import rawpy, os, csv
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

def extract_color_channels(image):
    """Extract Red, Green, and Blue color channels from a Bayer RAW image."""
    # Bayer pattern: SBGGR (Blue in top-left)
    B = image[0::2, 0::2]     # Blue pixels (even rows and even columns)
    G1 = image[0::2, 1::2]    # Green pixels (even rows, odd columns)
    G2 = image[1::2, 0::2]    # Green pixels (odd rows, even columns)
    R = image[1::2, 1::2]     # Red pixels (odd rows and odd columns)

    # Average the two green channels
    G = (G1 + G2) / 2

    return R, G, B

def circular_roi_mean(image, diameter=20):
    """Compute the mean pixel value and 1-sigma uncertainty within a circular ROI at the center of the image."""
    radius = diameter // 2
    center_y, center_x = image.shape[0] // 2, image.shape[1] // 2

    y, x = np.ogrid[:image.shape[0], :image.shape[1]]
    mask = (x - center_x)**2 + (y - center_y)**2 <= radius**2
    roi_values = image[mask] # Extract pixel values within circular mask

    N = len(roi_values)
    # Calculate mean intensity inside ROI which corresponds to constant*BRDF.
    mean_val = np.mean(roi_values)
    # Simple statistical analysis using 1-sigma
    std_val = np.std(roi_values)
    sigma = std_val / np.sqrt(N) 
    relative_error = sigma/mean_val 

    return float(mean_val)

def generate_zemax_bsdf_file(
    filename: str,
    symmetry: str,
    spectral_content: str,
    scatter_type: str,
    sample_rotations: list[int],
    incidence_angles: list[int],
    azimuth_angles: list[int],
    radial_angles: list[int],
    tis_data: dict,
    bsdf_data: dict,
):
    """
    Generates a Zemax Tabular BSDF file.

    Args:
        filename (str): Path to save the .BSDF file.
        symmetry (str): One of 'PlaneSymmetrical', 'Asymmetrical', 'Asymmetrical4D'.
        spectral_content (str): 'Monochrome' or 'XYZ'.
        scatter_type (str): 'BRDF' or 'BTDF'.
        sample_rotations (list): List of sample rotation angles.
        incidence_angles (list): List of angle of incidence values.
        azimuth_angles (list): List of azimuth angles.
        radial_angles (list): List of radial angles.
        tis_data (dict): TIS values, format: { (rot, inc): TIS_value }
        bsdf_data (dict): BSDF values, format: { (rot, inc): 2D array [azimuth][radial] }
    """

    def write_header(f):
        f.write("# Data Generated by Python BSDF Generator\n")
        f.write(f"# {datetime.now().strftime('%m/%d/%Y %I:%M:%S %p')}\n")
        f.write("Source  Measured\n")
        f.write(f"Symmetry  {symmetry}\n")
        f.write(f"SpectralContent  {spectral_content}\n")
        f.write(f"ScatterType  {scatter_type}\n")

        f.write(f"SampleRotation {len(sample_rotations)}\n")
        f.write("\t".join(map(str, sample_rotations)) + "\n")

        f.write(f"AngleOfIncidence  {len(incidence_angles)}\n")
        f.write("\t".join(map(str, incidence_angles)) + "\n")

        f.write(f"ScatterAzimuth {len(azimuth_angles)}\n")
        f.write("\t".join(map(str, azimuth_angles)) + "\n")

        f.write(f"ScatterRadial {len(radial_angles)}\n")
        f.write("\t".join(map(str, radial_angles)) + "\n\n")

    def write_data_block(f, component_index: int, label: str):
        f.write(f"{label}\n")
        f.write("DataBegin\n")

        for rot in sample_rotations:
            for inc in incidence_angles:
                key = (rot, inc)
                tis = tis_data.get(key, 0.0)
                grid = bsdf_data.get(key)

                if grid is None:
                    raise ValueError(f"Missing BSDF data for rotation={rot}, incidence={inc}")

                f.write(f"TIS {tis:.2f}\n")

                for row in grid:
                    line = []
                    for triple in row:
                        val = triple[component_index] if triple is not None else 0.0
                        line.append(f"{val:.3E}")
                    f.write("\t".join(line) + "\n")

        f.write("DataEnd\n\n")

    with open(filename, 'w') as f:
        write_header(f)
        write_data_block(f, component_index=0, label="TristimulusX")
        write_data_block(f, component_index=1, label="TristimulusY")
        write_data_block(f, component_index=2, label="TristimulusZ")

